Repository ErisApps/POI, pull requests merged in 2021-04, with the labels that each got.

#30 Feature/minor improvements
  PoiDiscordDotNet/Bootstrapper.cs
Labels: bug, enhancement

#35 Added Difficulty text / Moved every other stat down
  PoiDiscordDotNet/Commands/Beat Saber/BaseSongCommand.cs
Labels: enhancement

#36 Set the culture to be consistent across different machines/dev environment
  PoiDiscordDotNet/Bootstrapper.cs
Labels: enhancement

#37 Bump docker .NET runtime from 5.0.4 to 5.0.5
  PoiDiscordDotNet/Dockerfile
Labels: dependencies

#44 Feature/workaround score saber internal server error responses
  PoiDiscordDotNet/Services/ScoreSaberService.cs
Labels: bug, enhancement

#46 Fixed Structured Logging warnings
  PoiDiscordDotNet/Bootstrapper.cs
  PoiDiscordDotNet/Services/ConfigProviderService.cs
  PoiDiscordDotNet/Services/MongoDbService.cs
  PoiDiscordDotNet/Services/UptimeManagementService.cs
Labels: enhancement

#48 Improved Score command error logging
  POI.DiscordDotNet/Commands/Beat Saber/BaseSongCommand.cs
  POI.DiscordDotNet/Extensions/LoggerExtensions.cs
Labels: enhancement

#45 Added Dependabot config file
  .github/dependabot.yml
Labels: enhancement

#49 Reworked Dockerfile for new architecture
  .dockerignore
  POI.DiscordDotNet.Dockerfile
  POI.DiscordDotNet/Dockerfile
Labels: enhancement

#50 Fixed Dependabot config file
  .github/dependabot.yml
Labels: bug, dependencies

#51 Yet another attempt at fixing the Dependabot config file
  .github/dependabot.yml
Labels: bug, dependencies
